/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kinematics.gui.labcreator;

import java.awt.BorderLayout;

/**
 *
 * @author grzes
 */
public class BoardDesigner extends javax.swing.JPanel
{
    //private LabDesignerPrev labDesigner;
    private LabDesigner labDesigner;
    private ArmDesigner armDesigner;
    
    /**
     * Creates new form BoardDesigner
     */
    public BoardDesigner()
    {
        initComponents();
        armDesContainer.setLayout(new BorderLayout());
        labDesContainer.setLayout(new BorderLayout());
    }

    public void setArmDesigner(ArmDesigner armDes)
    {
        armDesigner = armDes;
        armDesContainer.removeAll();
        armDesContainer.add(armDes);
    }

    /*public void setLabDesigner(LabDesignerPrev labDes)
    {
        labDesigner = labDes;
        labDesContainer.removeAll();
        labDesContainer.add(labDes);
    }*/

    public void setLabDesigner(LabDesigner labDes)
    {
        labDesigner = labDes;
        labDesContainer.removeAll();
        labDesContainer.add(labDes);
    }
    
    public BoardData getBoardData()
    {
        return new BoardData(armDesigner.armData, labDesigner.labData);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSplitPane1 = new javax.swing.JSplitPane();
        labDesContainer = new javax.swing.JPanel();
        armDesContainer = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(400);

        javax.swing.GroupLayout labDesContainerLayout = new javax.swing.GroupLayout(labDesContainer);
        labDesContainer.setLayout(labDesContainerLayout);
        labDesContainerLayout.setHorizontalGroup(
            labDesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        labDesContainerLayout.setVerticalGroup(
            labDesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(labDesContainer);

        javax.swing.GroupLayout armDesContainerLayout = new javax.swing.GroupLayout(armDesContainer);
        armDesContainer.setLayout(armDesContainerLayout);
        armDesContainerLayout.setHorizontalGroup(
            armDesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        armDesContainerLayout.setVerticalGroup(
            armDesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(armDesContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel armDesContainer;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel labDesContainer;
    // End of variables declaration//GEN-END:variables
}
